[2024-05-19T00:12:22.075+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: Real_Estate_Webscraping_ETL.Ingest_Data_from_Redfin scheduled__2024-05-17T12:59:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
