[2024-05-15T23:22:31.968+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T23:22:31.999+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Webscrape.Process_Send_Data manual__2024-05-15T23:22:30.003618+00:00 [queued]>
[2024-05-15T23:22:32.007+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Webscrape.Process_Send_Data manual__2024-05-15T23:22:30.003618+00:00 [queued]>
[2024-05-15T23:22:32.008+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-15T23:22:32.018+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Process_Send_Data> on 2024-05-15 23:22:30.003618+00:00
[2024-05-15T23:22:32.032+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Webscrape', 'Process_Send_Data', 'manual__2024-05-15T23:22:30.003618+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/webscrapping.py', '--cfg-path', '/tmp/tmpbuw404n_']
[2024-05-15T23:22:32.034+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=568) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-15T23:22:32.034+0000] {standard_task_runner.py:91} INFO - Job 146: Subtask Process_Send_Data
[2024-05-15T23:22:32.035+0000] {standard_task_runner.py:63} INFO - Started process 574 to run task
[2024-05-15T23:22:32.062+0000] {task_command.py:426} INFO - Running <TaskInstance: Webscrape.Process_Send_Data manual__2024-05-15T23:22:30.003618+00:00 [running]> on host fb6491796190
[2024-05-15T23:22:32.112+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='svc' AIRFLOW_CTX_DAG_ID='Webscrape' AIRFLOW_CTX_TASK_ID='Process_Send_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-15T23:22:30.003618+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-15T23:22:30.003618+00:00'
[2024-05-15T23:22:32.114+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T23:22:32.128+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2024-05-15T23:22:32.128+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 2g --driver-memory 2g --name arrow-spark --deploy-mode cluster dags/includes/jobs/spark_consumer.py
[2024-05-15T23:22:33.285+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: Cluster deploy mode is currently not supported for python applications on standalone clusters.
[2024-05-15T23:22:33.286+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:1047)
[2024-05-15T23:22:33.287+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:293)
[2024-05-15T23:22:33.287+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
[2024-05-15T23:22:33.287+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2024-05-15T23:22:33.287+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2024-05-15T23:22:33.287+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2024-05-15T23:22:33.287+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-05-15T23:22:33.288+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-05-15T23:22:33.288+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-05-15T23:22:33.308+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T23:22:33.350+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 2g --driver-memory 2g --name arrow-spark --deploy-mode cluster dags/includes/jobs/spark_consumer.py. Error code is: 1.
[2024-05-15T23:22:33.356+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Webscrape, task_id=Process_Send_Data, run_id=manual__2024-05-15T23:22:30.003618+00:00, execution_date=20240515T232230, start_date=20240515T232232, end_date=20240515T232233
[2024-05-15T23:22:33.367+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 146 for task Process_Send_Data (Cannot execute: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 2g --driver-memory 2g --name arrow-spark --deploy-mode cluster dags/includes/jobs/spark_consumer.py. Error code is: 1.; 574)
[2024-05-15T23:22:33.410+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-15T23:22:33.467+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T23:22:33.470+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
