[2024-05-14T17:43:04.119+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: Webscrapper.Ingest_Data manual__2024-05-14T15:41:35.663636+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
