[2024-05-14T18:01:25.604+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T18:01:25.636+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Webscrape.Process_Send_Data manual__2024-05-14T17:59:19.217649+00:00 [queued]>
[2024-05-14T18:01:25.642+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Webscrape.Process_Send_Data manual__2024-05-14T17:59:19.217649+00:00 [queued]>
[2024-05-14T18:01:25.642+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-05-14T18:01:25.652+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Process_Send_Data> on 2024-05-14 17:59:19.217649+00:00
[2024-05-14T18:01:25.666+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=495) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-14T18:01:25.667+0000] {standard_task_runner.py:63} INFO - Started process 496 to run task
[2024-05-14T18:01:25.666+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Webscrape', 'Process_Send_Data', 'manual__2024-05-14T17:59:19.217649+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/webscrapping.py', '--cfg-path', '/tmp/tmpj69m5pca']
[2024-05-14T18:01:25.668+0000] {standard_task_runner.py:91} INFO - Job 85: Subtask Process_Send_Data
[2024-05-14T18:01:25.718+0000] {task_command.py:426} INFO - Running <TaskInstance: Webscrape.Process_Send_Data manual__2024-05-14T17:59:19.217649+00:00 [running]> on host 4ac0c9fa8b6a
[2024-05-14T18:01:25.767+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='svc' AIRFLOW_CTX_DAG_ID='Webscrape' AIRFLOW_CTX_TASK_ID='Process_Send_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T17:59:19.217649+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-14T17:59:19.217649+00:00'
[2024-05-14T18:01:25.768+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T18:01:25.909+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T18:01:25.912+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/includes/jobs/spark_consumer.py", line 68, in process_start
    .getOrCreate())
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-05-14T18:01:25.938+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Webscrape, task_id=Process_Send_Data, run_id=manual__2024-05-14T17:59:19.217649+00:00, execution_date=20240514T175919, start_date=20240514T180125, end_date=20240514T180125
[2024-05-14T18:01:25.957+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 85 for task Process_Send_Data ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 496)
[2024-05-14T18:01:25.975+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-14T18:01:25.988+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-14T18:01:25.989+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
