[2024-05-19T00:13:11.821+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: Real_Estate_Webscraping_ETL.Process_and_Send_Data_to_DB scheduled__2024-05-18T12:03:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
